import java.util.*;
class TryCatch
{
	public static void main(String args[])
	{
		int a;
		Scanner sc=new Scanner(System.in);
		System.out.println("Enter two Numbers for Dision :");
		a=sc.nextInt();
		try
		{
			if(a>18)
			{
				throw new Exception();
			}
		}
		catch(Exception e)
		{
			System.out.println("Arithmetic Exception Dision divided by Zero Occured");
		}
		finally
		{
			System.out.println("Finally Block executes in whatever may be the case");
		}
		
	}
}
