import java.util.*;
class TryCatch
{
	public static void main(String args[])
	{
		int a,b,c=0;
		Scanner sc=new Scanner(System.in);
		System.out.println("Enter two Numbers for Dision :");
		a=sc.nextInt();
		b=sc.nextInt();
		try
		{
			c=a/b;
			System.out.println("Result of Division performed :"+c);
		}
		catch(Exception e)
		{
			System.out.println("Arithmetic Exception Dision divided by Zero Occured");
		}
		finally
		{
			System.out.println("Finally Block executes in whatever may be the case");
		}
		
	}
}
